### ISSUE TITLE
4.x Feature Planning

### ISSUE THREAD

**Issue by alexbevi** [alexbevi/redmine_knowledgebase#237]
This is meant to serve as a potential roadmap for the next major release. Feel free to drop ideas as comments, or create feature requests as per usual :)
- [ ] Versioned Article Ratings (#209)
- [ ] Email Notifications Toggle (per category / article) (#226)
- [ ] Ensure Attachment Removal adheres to user permissions (#199)
- [ ] Publicly viewable Knowledgebase for Public Projects (#187, #186)
- [ ] Add article to issue via an autocomplete dialog (#165)
- [ ] Better landing page layout (ideas welcome, #148)
- [ ] Single Rating per User (#114)
- [ ] Revisit Granular content access (whitelist was a good POC, but is not the most ideal solution, #143)

**Comment by jankap** [comment]
I agree with @alesak and @MadEgg that it would be awesome to have one global KB with the ability to link to from different projects. So we can keep one KB clean and up to date and may use e.g. the wiki or another KB for project dependend problems/workarounds/etc.

**Comment by zoeeer** [comment]
Allow me to list my most expected features for knowledge base:

- [ ] Draft saving and publishing
- [ ] Category ordering manually
- [ ] Allow expand category tree (on the sidebar of landing page) to show article titles (#365)

2 and 3 are both about more functionalities in category management. I find it might be helpful if we turn the categories into something like TOC.

Also, for the "Better landing page layout" part, I will recommend to show TOC in the main part, and move the "latest" to alongside with "most views" and "highest rating" part. But at least having TOC in the sidebar would be a great start.
